apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-springboot-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: spring-boot
  template:
    metadata:
      labels:
        app: spring-boot
    spec:
      containers:
      - name: my-spring-boot
        image: niviacr.azurecr.io/spring-boot:#{Build.BuildId}#
        imagePullPolicy: Always
        ports:
        - containerPort: 8085
# service type loadbalancer
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: spring-boot
    k8s-app: spring-boot
  name: spring-boot
spec:
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 8080
  type: LoadBalancer
  selector:
    app: spring-boot