# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  name: 'nivi-agent-pool'

steps:
- task: Maven@3
  inputs:
    mavenPomFile: 'pom.xml'
    goals: 'clean package'
    options: '-DforkCount=0 -DargLine="-Xmx1024m -Xms512m"'

- task: Docker@2
  inputs:
    containerRegistry: 'nivi-acr-connection'
    repository: 'spring-boot'
    command: 'buildAndPush'
    Dockerfile: 'Dockerfile'
    buildContext: '.'
    tags: |
      $(Build.BuildId)
      latest

- task: Kubernetes@1
  displayName: 'Apply Kubernetes YAML'
  inputs:
    connectionType: 'Azure Resource Manager'
    azureSubscriptionEndpoint: 'nivi-aks-service-connection'
    azureResourceGroup: 'nivi-resource-group'
    kubernetesCluster: 'nivi-aks-cluster'
    namespace: 'default'
    command: 'apply'
    useConfigurationFile: true
    configuration: 'aks-deploy-from-acr.yml'